export const contacts = {
  GETALL_CONTACTS: "GETALL_CONTACTS",
  GETALL_CONTACTS_SUCCESS: "GETALL_CONTACTS_SUCCESS",

  CREATE_CONTACT: "CREATE_CONTACT",
  CREATE_CONTACT_SUCCESS: "CREATE_CONTACT_SUCCESS",

  UPDATE_CONTACT: "UPDATE_CONTACT",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",

  UPDATE_FAVOURITE_CONTACT: "UPDATE_FAVOURITE_CONTACT",
  UPDATE_FAVOURITE_CONTACT_SUCCESS: "UPDATE_FAVOURITE_CONTACT_SUCCESS",

  DELETE_CONTACT: "DELETE_CONTACT",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",

  CONTACTS_REQUEST_FAILED: "CONTACTS_REQUEST_FAILED",
};
