export const users = {
  SIGNIN_USER: "SIGNIN_USER",
  SIGNIN_USER_SUCCESS: "SIGNIN_USER_SUCCESS",

  SIGNUP_USER: "SIGNUP_USER",
  SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",

  SIGNOUT_USER: "SIGNOUT_USER",

  GET_USER_DETAIL: "GET_USER_DETAIL",
  GET_USER_DETAIL_SUCCESS: "GET_USER_DETAIL_SUCCESS",

  USER_REQUEST_FAILED: "USER_REQUEST_FAILED",
};
