name: Contact-manager CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies and build the frontend (app)
      - name: Install dependencies (Frontend)
        run: yarn install --frozen-lockfile
        working-directory: app

      - name: Build frontend
        run: yarn build
        working-directory: app

      # Install dependencies and build the backend (server)
      - name: Install dependencies (Backend)
        run: yarn install --frozen-lockfile
        working-directory: server

      - name: Build backend
        run: yarn build
        working-directory: server

      - name: Run backend tests
        run: yarn test
        working-directory: server
